In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

import numpy as np

import random

Creating a basic tensor, tensors are arrays used to represent and manipulate numerical data in deep learning. They serve as the foundational data structure for building and training neural network models.

In [3]:
tensor_x = torch.tensor([random.randint(0, 10) for _ in range(4)])
tensor_y = torch.tensor([random.randint(0, 10) for _ in range(4)])

print("Tensor x:",tensor_x)
print("Tensor y:",tensor_y)

print("Sum of tensors:", tensor_x + tensor_y)
print("Substraction of tensors:", tensor_x - tensor_y)
print("Multiplication of tensors:", tensor_x * tensor_y)

Tensor x: tensor([2, 1, 5, 5])
Tensor y: tensor([6, 7, 6, 7])
Sum of tensors: tensor([ 8,  8, 11, 12])
Substraction of tensors: tensor([-4, -6, -1, -2])
Multiplication of tensors: tensor([12,  7, 30, 35])


Creating basic neural network, in features have to be the same size as the length of the input features (original tensor and output of neurons). 


In [4]:
input = torch.Tensor([[random.randint(0, 10) for _ in range(6)]])
print(input)

#Small Neural Network
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=3),  
    nn.Linear(in_features=3, out_features=1)   
)

output = model(input)
print(output)

tensor([[7., 0., 2., 8., 9., 5.]])
tensor([[-0.5542]], grad_fn=<AddmmBackward0>)


### Sigmoid VS Softmax
Sigmoid is an activation function that is mainly used in binary classification. Output bounday is usually 0.5. 
Softmax is an activation function that is mainly used in multi-classs scenarios. Predicted class is the one with highest probability.

In [5]:

input= torch.Tensor([[random.randint(0, 10) for _ in range(8)]])
print(input)

model = nn.Sequential(
  nn.Linear(in_features=8, out_features=1),
  nn.Sigmoid()
)

output = model(input)
print(output)

tensor([[7., 8., 4., 6., 7., 4., 8., 6.]])
tensor([[0.5199]], grad_fn=<SigmoidBackward0>)


In [6]:

input = torch.Tensor([[random.randint(0, 10) for _ in range(11)]])
print(input)

#Neural Network with 3 hidden neurons
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 10),
  nn.Linear(10, 4),
  nn.Softmax()
)


output = model(input)
print(output)

tensor([[ 5.,  0.,  2.,  3., 10.,  6.,  3.,  5.,  8.,  1.,  4.]])
tensor([[0.1151, 0.7037, 0.1034, 0.0778]], grad_fn=<SoftmaxBackward0>)


c:\Users\juang\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py:1518: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


### Loss Function 
Function that determines how well your model is performing, comparing y_pred vs y. 
Uses One-hot encoding, transforming true label to a tensor of 1 and 0s.


### Ways to reduce loss function

- Backpropagation computes gradients of the loss with respect to the model parameters
- Updating learning rate to find the global minimun
- Updating parameters, like substracting local gradients by learning rate to the weights 
- PyTorch uses optimizers, takes cares of the weights, most common un stochastic gradient descent (SGD)

In [8]:

X = torch.randn((100, 10)) 
y = torch.randint(0, 5, (100,)) #there are 5 classes

dataset = TensorDataset(X, y)

model = nn.Sequential(
    nn.Linear(10, 50),
    nn.Linear(50, 5), #Output 5 features, as there are 5 classes
    nn.Softmax() 
)

# Loss function for multiclass classification
criterion = nn.CrossEntropyLoss()

# Optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001)

dataloader = DataLoader(dataset, shuffle=True)

epochs = 10 #number of iterations

for epoch in range(epochs):
    for data in dataloader:
        # Set the gradients to zero
        optimizer.zero_grad()
        
        # Run a forward pass
        feature, target = data
        prediction = model(feature)    
        
        loss = criterion(prediction, target)    
        
        loss.backward()
        
        optimizer.step()

    print(f'Loss: {loss.item()}')



Loss: 1.6885645389556885
Loss: 1.6712253093719482
Loss: 1.581771969795227
Loss: 1.7591716051101685
Loss: 1.6457157135009766
Loss: 1.731720209121704
Loss: 1.5870938301086426
Loss: 1.6528093814849854
Loss: 1.4827433824539185
Loss: 1.7308361530303955
